version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - "${ADMINER_PORT}:8080"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./server/src:/app/src        # live code reload (mvn run re-compiles)
      - ~/.m2:/root/.m2              # use host maven cache

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - server
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mysql_data:
